version: '3.8'
services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yaml  # Match the correct file name
    volumes:
    - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml  # Correct mapping
    - /Users/s.m.ahadalichowdhury/Downloads/project/observability/1st-try/logs:/app/logs
